### ISSUE TITLE
fix 2KHz offset in Tx

### ISSUE THREAD

**Issue by manostheodoridis** [librespacefoundation/upsat-comms-software#17]
Set FREQ0 register to 0x34.
This value will help us achieve 435.800049 MHz instead of the current 435.802002, due to the fact that the current value of FREQ0 register is 0x54.

**Comment by manostheodoridis** [comment]
Due to the fact that the crystal of Tx CC1120 is not exactly 32 Mhz we are calibrating through trial and error .

**Comment by surligas** [comment]
Fixed.
