### ISSUE TITLE
investigate the implementation of GFSK

### ISSUE THREAD

**Issue by manostheodoridis** [librespacefoundation/upsat-comms-software#19]

**Comment by surligas** [comment]
@manostheodoridis can you please provide the registers from the RF Studio to check them? Take care the frequency deviation. I think that it the half for the GFSK, But maybe I am wrong...

**Comment by manostheodoridis** [comment]
The differances between  FSK and GFSK are located  the following registers  

SYNC_CFG1    and
MODCFG_DEV_E .
At SYNC_CFG1 it seems that its SYNC_THR* part changes.
At MODCFG_DEV_E register it seems that its MOD_FORMAT* part changes.

(*SYNC_THR :Soft decision sync word threshold. A sync word is accepted when the calculated sync
word qualifier value (PQT_SYNC_ERR.SYNC_ERROR) is less than SYNC_THR/2). A low
threshold value means a strict sync word qualifier (sync word must be of high quality to
be accepted) while a high threshold value will accept sync word of a poorer quality
(increased probability of detecting ‘false’ sync words)

 *MOD_FORMAT:  Modulation format)


 
435.765015
FSK
SYNC_CFG1              0x0B
MODCFG_DEV_E      0x03

GFSK
SYNC_CFG1             0x08
MODCFG_DEV_E     0x0B
