### ISSUE TITLE
investigate MSK implementation 

### ISSUE THREAD

**Issue by manostheodoridis** [librespacefoundation/upsat-comms-software#32]
By setting the frequency deviation to 1/4 of the symbol rate, we expect the phase shifts to be performed with a constant transition time. 

In our case with 9.6 ksps and by setting the Frequency Deviation 2.4 kHz, we anticipate an Actual Modulation Index of 0.49958.

must set:
DEVIATION_M -> 0x3A
MODCFG_DEV_E -> 0x02

**Comment by surligas** [comment]
At the next satellite!
