### ISSUE TITLE
Downlink new frequency 435.765 MHz?

### ISSUE THREAD

**Issue by manostheodoridis** [librespacefoundation/upsat-comms-software#39]
For 435.765 MHz we should set as a starting point:
FS_CFG -> 0x14

FREQ2   -> 0x6C
FREQ1   -> 0xF0
FREQ0   -> 0xF6

**Comment by surligas** [comment]
@manostheodoridis we have at least -3.5 kHz of frequency drift. Can we adjust a little the values?

**Comment by manostheodoridis** [comment]
maybe try 

FS_CFG -> 0x14

FREQ2 -> 0x6C
FREQ1 -> 0xF1
FREQ0 -> 0x2F

to have +3.5 kHz

**Comment by surligas** [comment]
Ok i will test them ASAP

**Comment by surligas** [comment]
Fixed e4f69534284826d576dd3596beca69392ec8cc59
