### ISSUE TITLE
Store WOD from OBC extract info and transmit it every 30 secs

### ISSUE THREAD

**Issue by surligas** [librespacefoundation/upsat-comms-software#61]

**Comment by surligas** [comment]
The WOD storage is ready. What we should transmit if no WOD is available? @ppapadeas @nchronas

**Comment by ppapadeas** [comment]
We should transmit all zeros as per specification.

**Comment by surligas** [comment]
Ok, I will provide the patch asap.

**Comment by surligas** [comment]
Fixed 993f1d3deedd7eb48d279332595d164500cef332
