### ISSUE TITLE
Eccs hk size of data

### ISSUE THREAD

**Issue by nchronas** [librespacefoundation/upsat-comms-software#78]
@surligas In the file
https://github.com/librespacefoundation/ecss_services/blob/master/platform/comms/housekeeping.c
you are using sizeof of for updating the size of the packet. Please make sure that sizeof returns correct values for uint8-t,uint16-t,uint32-t etc in GCC because I had issues with IAR.

**Comment by surligas** [comment]
GNU rulezzz http://www.gnu.org/software/libc/manual/html_node/Integers.html

**Comment by surligas** [comment]
End of discussion :P
